//! hotl — one binary, three capabilities (watch · orchestrate · execute).
//!
//! Subcommands:
//!   (none)        the agent REPL (execute — the M0 default flip, merge plan 0002)
//!   -p "prompt"   headless one-shot; asks default-deny (Sec #11); --json for events
//!   watch         the tmux dashboard (the pre-merge `hotl`)
//!   fleet         reserved (orchestrate, M4+)
//!   doctor        environment/setup checks (MD)
//!   update        reserved (MD)

mod agent;
mod doctor;
mod watch;

/// The zsh `:` prefix (Forge, corpus 11): a line starting with `: ` becomes
/// an agent prompt; everything else runs as normal shell.
const ZSH_PLUGIN: &str = r#"# hotl zsh plugin — generated by `hotl init zsh`
# A command line starting with `: ` becomes an agent prompt (hotl -p).
hotl-accept-line() {
  if [[ $BUFFER == ':'\ * ]]; then
    local prompt_text=${BUFFER#: }
    BUFFER="hotl -p ${(qq)prompt_text}"
  fi
  zle .accept-line
}
zle -N accept-line hotl-accept-line
"#;

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("watch") => {
            if let Err(e) = watch::watch_main() {
                eprintln!("hotl watch: {e}");
                std::process::exit(1);
            }
        }
        Some("fleet") => {
            eprintln!("hotl fleet (orchestrate) is reserved and not built yet — it arrives after the harness's M4 seams. See docs/exec-plans/active/0001-harness-build.md.");
            std::process::exit(2);
        }
        Some("doctor") => std::process::exit(doctor::doctor_main()),
        Some("update") => {
            eprintln!("`hotl update` is reserved for the distribution milestone (MD) and not built yet.");
            std::process::exit(2);
        }
        Some("init") => {
            // Binary-generated shell integration (0001 §M1, Forge's `:` prefix).
            match args.get(1).map(String::as_str) {
                Some("zsh") => print!("{}", ZSH_PLUGIN),
                _ => {
                    eprintln!("usage: hotl init zsh   # then: eval \"$(hotl init zsh)\" in ~/.zshrc");
                    std::process::exit(2);
                }
            }
        }
        Some("--help") | Some("-h") | Some("help") => {
            println!(
                "hotl — human on the loop\n\n\
                 USAGE:\n  hotl                 agent REPL (execute)\n  \
                 hotl -p \"prompt\"     headless one-shot (add --json for a JSONL event stream)\n  \
                 hotl watch           tmux agent dashboard (watch)\n  \
                 hotl init zsh        print the zsh `:` prefix plugin (eval it in ~/.zshrc)\n  \
                 hotl doctor          check provider keys, sandbox, config, session store\n  \
                 hotl fleet           reserved (orchestrate)\n\n\
                 ENV:\n  HOTL_MODEL             provider/model, e.g. anthropic/{} or openai/gpt-5\n  \
                 ANTHROPIC_API_KEY      for the anthropic provider (the default)\n  \
                 OPENAI_API_KEY         for openai; HOTL_OPENAI_BASE_URL for compatible endpoints\n  \
                 HOTL_SANDBOX=off       disable the bash sandbox floor (marked in every ask)\n\n\
                 REPL: type to prompt · type mid-turn to steer · ctrl-c interrupts a turn\n\
                 Allow rules: ~/.config/hotl/permissions.toml (see docs)",
                hotl_provider_anthropic::DEFAULT_MODEL
            );
        }
        _ => {
            // The agent surface. One-shot CLI runs current_thread per the
            // async policy (no pool spinup on the cold-start path).
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("tokio runtime");
            let code = rt.block_on(agent::agent_main(args));
            std::process::exit(code);
        }
    }
}
